-- Bean Counter Database Setup
-- ============================
--
-- This project uses Supabase CLI migrations.
-- See: supabase/migrations/
--
-- For a fresh database, run all migrations in order:
--   1. 20240101000000_initial_schema.sql
--   2. 20241225000000_add_transaction_type.sql
--
-- Or use the Supabase CLI:
--   supabase db push
--
-- For existing databases, run only the new migrations you haven't applied yet.
